name: example
publish_to: none
description: >-
  Simple project that demonstrates how to open maps application
  (or browser) from widgets

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.4

dependencies:
  flutter:
    sdk: flutter

  maps_launcher:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
