name: maps_launcher
description: Simple Flutter plugin to open the maps application (or browser) on all platforms.
version: 2.3.0
homepage: https://github.com/pikaju/flutter-maps-launcher

environment:
  sdk: ^3.5.0
  flutter: ^3.24.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.maps_launcher
        pluginClass: MapsLauncherPlugin
      ios:
        pluginClass: MapsLauncherPlugin
      windows:
        pluginClass: MapsLauncherPlugin
      macos:
        pluginClass: MapsLauncherPlugin
      linux:
        pluginClass: MapsLauncherPlugin
      web:
        pluginClass: MapsLauncherWeb
        fileName: maps_launcher_web.dart
